### ISSUE TITLE
Set up ORM

### ISSUE THREAD

**Issue by priyanshumahey** [priyanshumahey/Team-Management#22]
Set up an ORM (one option is TypeORM) and create some basic guidelines on how to work with it for this project.

**Comment by jtsang02** [comment]
I haven't had a chance to look into TypeORM but I will aim to have this setup with basic guidlines before our next meeting.

Please see my progress on this branch. I've setup a NodeJS + Express + MySQL backend with some basic Rest APIs.  I followed this tutorial: https://www.bezkoder.com/react-node-express-mysql/#Define_the_Sequelize_Model

The Rest APIs perform CRUD operations on a specific database as specified in the `db.config.ts` file.  However, since we want a database created for each team I wonder how this architecture would change.  I think we'll have a better idea once the system design is completed.
